-- Sqrubber version 0.3.0
-- Sqrubber output generated on 2017-11-01 13:36:42.153336




--
-- Sqrubber is assuming the existence of schema myschema
--


-- SQL Dump of DB_1.mdb
-- generated by MDB Viewer 2.2.7
-- optimized for PostgreSQL

SET NAMES 'UTF8';



DROP TABLE IF EXISTS myschema.der_all_brands_price_data;

CREATE TABLE myschema.der_all_brands_price_data (
     market TEXT,
     name TEXT,
     store_num INTEGER,
     category TEXT,
     item TEXT,
     size_or_quantity TEXT,
     price DOUBLE PRECISION,
     date TEXT
);

INSERT INTO myschema.der_all_brands_price_data (market, name, store_num, category, item, size_or_quantity, price, date)
    VALUES(E'Albany',E'Cumberland Farms',478,E'Beverage',E'Coffee',E'Small - 12 oz.',0.99,E'April 2013'),
          (E'Albany',E'Cumberland Farms',476,E'Beverage',E'Coffee',E'Small - 12 oz.',0.99,E'April 2013'),
          (E'Albany',E'Cumberland Farms',473,E'Beverage',E'Coffee',E'Small - 12 oz.',0.99,E'April 2013'),
          (E'Albany',E'Cumberland Farms',472,E'Beverage',E'Coffee',E'Small - 12 oz.',0.99,E'April 2013'),
          (E'Albany',E'Cumberland Farms',477,E'Beverage',E'Coffee',E'Small - 12 oz.',0.99,E'April 2013');

DROP TABLE IF EXISTS myschema.der_all_brands_transposed;

CREATE TABLE myschema.der_all_brands_transposed (
     name TEXT,
     store_num INTEGER,
     category TEXT,
     item TEXT,
     size_or_quantity TEXT,
     price DOUBLE PRECISION
);

INSERT INTO myschema.der_all_brands_transposed (name, store_num, category, item, size_or_quantity, price)
    VALUES(E'Cumberland Farms',478,E'Beverage',E'Coffee',E'Small - 12 oz.',0.99),
          (E'Cumberland Farms',476,E'Beverage',E'Coffee',E'Small - 12 oz.',0.99),
          (E'Cumberland Farms',473,E'Beverage',E'Coffee',E'Small - 12 oz.',0.99),
          (E'Cumberland Farms',472,E'Beverage',E'Coffee',E'Small - 12 oz.',0.99),
          (E'Cumberland Farms',477,E'Beverage',E'Coffee',E'Small - 12 oz.',0.99),
          (E'Cumberland Farms',474,E'Beverage',E'Coffee',E'Small - 12 oz.',0.99);

DROP TABLE IF EXISTS myschema.der_category_master;

CREATE TABLE myschema.der_category_master (
     name TEXT,
     category TEXT,
     item TEXT,
     common_category TEXT,
     common_sub_category TEXT,
     common_item TEXT
);

INSERT INTO myschema.der_category_master (name, category, item, common_category, common_sub_category, common_item)
    VALUES(E'Independent',E'Beverage',E'Iced Coffee',E'Beverages',E'Cold Beverages',E'Iced Coffee'),
          (E'Independent',E'Bakery',E'Muffins',E'Breakfast',E'Bakery',E'Muffins'),
          (E'Independent',E'Beverage',E'Frozen Coffee Drink',E'Beverages',E'Cold Beverages',E'Frozen Coffee Drinks');


-- SQL Dump of DB_2.mdb
-- generated by MDB Viewer 2.2.7
-- optimized for PostgreSQL

SET NAMES 'UTF8';



DROP TABLE IF EXISTS myschema.der_all_brands_price_data;

CREATE TABLE myschema.der_all_brands_price_data (
     market TEXT,
     name TEXT,
     store_num INTEGER,
     category TEXT,
     item TEXT,
     size_or_quantity TEXT,
     price DOUBLE PRECISION,
     date TEXT
);

INSERT INTO myschema.der_all_brands_price_data (market, name, store_num, category, item, size_or_quantity, price, date)
    VALUES(E'Atlanta',E'McDonald''s',264,E'Extra Value Meals',E'Bacon, Egg and Cheese Biscuit EVM',E'Meal',3.79,E'March 2013'),
          (E'Atlanta',E'McDonald''s',270,E'Extra Value Meals',E'Bacon, Egg and Cheese Biscuit EVM',E'Meal',4.29,E'March 2013'),
          (E'Atlanta',E'McDonald''s',282,E'Extra Value Meals',E'Bacon, Egg and Cheese Biscuit EVM',E'Meal',4.19,E'March 2013'),
          (E'Atlanta',E'McDonald''s',283,E'Extra Value Meals',E'Bacon, Egg and Cheese Biscuit EVM',E'Meal',4.19,E'March 2013'),
          (E'Atlanta',E'McDonald''s',284,E'Extra Value Meals',E'Bacon, Egg and Cheese Biscuit EVM',E'Meal',3.99,E'March 2013');


DROP TABLE IF EXISTS myschema.der_all_brands_transposed;

CREATE TABLE myschema.der_all_brands_transposed (
     name TEXT,
     store_num INTEGER,
     category TEXT,
     item TEXT,
     size_or_quantity TEXT,
     price DOUBLE PRECISION
);

INSERT INTO myschema.der_all_brands_transposed (name, store_num, category, item, size_or_quantity, price)
    VALUES(E'McDonald''s',264,E'Extra Value Meals',E'Bacon, Egg and Cheese Biscuit EVM',E'Meal',3.79),
          (E'McDonald''s',270,E'Extra Value Meals',E'Bacon, Egg and Cheese Biscuit EVM',E'Meal',4.29),
          (E'McDonald''s',282,E'Extra Value Meals',E'Bacon, Egg and Cheese Biscuit EVM',E'Meal',4.19),
          (E'McDonald''s',283,E'Extra Value Meals',E'Bacon, Egg and Cheese Biscuit EVM',E'Meal',4.19),
          (E'McDonald''s',284,E'Extra Value Meals',E'Bacon, Egg and Cheese Biscuit EVM',E'Meal',3.99),
          (E'McDonald''s',285,E'Extra Value Meals',E'Bacon, Egg and Cheese Biscuit EVM',E'Meal',3.79),
          (E'McDonald''s',286,E'Extra Value Meals',E'Bacon, Egg and Cheese Biscuit EVM',E'Meal',3.99);



-- Sqrubber job finished