-- SQL Dump of DB_1.mdb
-- generated by MDB Viewer 2.2.7
-- optimized for PostgreSQL

SET NAMES 'UTF8';



DROP TABLE IF EXISTS "All Brands Price Data";

CREATE TABLE "All Brands Price Data" (
    "Market" TEXT,
    "Name" TEXT,
    "Store #" INTEGER,
    "Category" TEXT,
    "Item" TEXT,
    "Size/Quantity" TEXT,
    "Price" DOUBLE PRECISION,
    "Date" TEXT
);

INSERT INTO "All Brands Price Data"("Market","Name","Store #","Category","Item","Size/Quantity","Price","Date")
VALUES(E'Albany',E'Cumberland Farms',478,E'Beverage',E'Coffee',E'Small - 12 oz.',0.99,E'April 2013'),
      (E'Albany',E'Cumberland Farms',476,E'Beverage',E'Coffee',E'Small - 12 oz.',0.99,E'April 2013'),
      (E'Albany',E'Cumberland Farms',473,E'Beverage',E'Coffee',E'Small - 12 oz.',0.99,E'April 2013'),
      (E'Albany',E'Cumberland Farms',472,E'Beverage',E'Coffee',E'Small - 12 oz.',0.99,E'April 2013'),
      (E'Albany',E'Cumberland Farms',477,E'Beverage',E'Coffee',E'Small - 12 oz.',0.99,E'April 2013');

DROP TABLE IF EXISTS "All Brands Transposed";

CREATE TABLE "All Brands Transposed" (
    "Name" TEXT,
    "Store #" INTEGER,
    "Category" TEXT,
    "Item" TEXT,
    "Size/Quantity" TEXT,
    "Price" DOUBLE PRECISION
);

INSERT INTO "All Brands Transposed"("Name","Store #","Category","Item","Size/Quantity","Price")
VALUES(E'Cumberland Farms',478,E'Beverage',E'Coffee',E'Small - 12 oz.',0.99),
      (E'Cumberland Farms',476,E'Beverage',E'Coffee',E'Small - 12 oz.',0.99),
      (E'Cumberland Farms',473,E'Beverage',E'Coffee',E'Small - 12 oz.',0.99),
      (E'Cumberland Farms',472,E'Beverage',E'Coffee',E'Small - 12 oz.',0.99),
      (E'Cumberland Farms',477,E'Beverage',E'Coffee',E'Small - 12 oz.',0.99),
      (E'Cumberland Farms',474,E'Beverage',E'Coffee',E'Small - 12 oz.',0.99);

DROP TABLE IF EXISTS "Category Master";

CREATE TABLE "Category Master" (
    "Name" TEXT,
    "Category" TEXT,
    "Item" TEXT,
    "Common Category" TEXT,
    "Common Sub-Category" TEXT,
    "Common Item" TEXT
);

INSERT INTO "Category Master"("Name","Category","Item","Common Category","Common Sub-Category","Common Item")
VALUES(E'Independent',E'Beverage',E'Iced Coffee',E'Beverages',E'Cold Beverages',E'Iced Coffee'),
      (E'Independent',E'Bakery',E'Muffins',E'Breakfast',E'Bakery',E'Muffins'),
      (E'Independent',E'Beverage',E'Frozen Coffee Drink',E'Beverages',E'Cold Beverages',E'Frozen Coffee Drinks');


-- SQL Dump of DB_2.mdb
-- generated by MDB Viewer 2.2.7
-- optimized for PostgreSQL

SET NAMES 'UTF8';



DROP TABLE IF EXISTS "All Brands Price Data";

CREATE TABLE "All Brands Price Data" (
    "Market" TEXT,
    "Name" TEXT,
    "Store #" INTEGER,
    "Category" TEXT,
    "Item" TEXT,
    "Size/Quantity" TEXT,
    "Price" DOUBLE PRECISION,
    "Date" TEXT
);

INSERT INTO "All Brands Price Data"("Market","Name","Store #","Category","Item","Size/Quantity","Price","Date")
VALUES(E'Atlanta',E'McDonald\'s',264,E'Extra Value Meals',E'Bacon, Egg and Cheese Biscuit EVM',E'Meal',3.79,E'March 2013'),
      (E'Atlanta',E'McDonald\'s',270,E'Extra Value Meals',E'Bacon, Egg and Cheese Biscuit EVM',E'Meal',4.29,E'March 2013'),
      (E'Atlanta',E'McDonald\'s',282,E'Extra Value Meals',E'Bacon, Egg and Cheese Biscuit EVM',E'Meal',4.19,E'March 2013'),
      (E'Atlanta',E'McDonald\'s',283,E'Extra Value Meals',E'Bacon, Egg and Cheese Biscuit EVM',E'Meal',4.19,E'March 2013'),
      (E'Atlanta',E'McDonald\'s',284,E'Extra Value Meals',E'Bacon, Egg and Cheese Biscuit EVM',E'Meal',3.99,E'March 2013');


DROP TABLE IF EXISTS "All Brands Transposed";

CREATE TABLE "All Brands Transposed" (
    "Name" TEXT,
    "Store #" INTEGER,
    "Category" TEXT,
    "Item" TEXT,
    "Size/Quantity" TEXT,
    "Price" DOUBLE PRECISION
);

INSERT INTO "All Brands Transposed"("Name","Store #","Category","Item","Size/Quantity","Price")
VALUES(E'McDonald\'s',264,E'Extra Value Meals',E'Bacon, Egg and Cheese Biscuit EVM',E'Meal',3.79),
      (E'McDonald\'s',270,E'Extra Value Meals',E'Bacon, Egg and Cheese Biscuit EVM',E'Meal',4.29),
      (E'McDonald\'s',282,E'Extra Value Meals',E'Bacon, Egg and Cheese Biscuit EVM',E'Meal',4.19),
      (E'McDonald\'s',283,E'Extra Value Meals',E'Bacon, Egg and Cheese Biscuit EVM',E'Meal',4.19),
      (E'McDonald\'s',284,E'Extra Value Meals',E'Bacon, Egg and Cheese Biscuit EVM',E'Meal',3.99),
      (E'McDonald\'s',285,E'Extra Value Meals',E'Bacon, Egg and Cheese Biscuit EVM',E'Meal',3.79),
      (E'McDonald\'s',286,E'Extra Value Meals',E'Bacon, Egg and Cheese Biscuit EVM',E'Meal',3.99);

